spring.application.name=rentedVehicle
spring.mongodb.uri=${MONGODB_URI:mongodb+srv://rentwheels:tacobell@rentwheels.hmialql.mongodb.net/?appName=rentwheels}
spring.mongodb.database=${MONGODB_DATABASE:rentwheels}
spring.data.mongodb.uri=${MONGODB_URI:mongodb+srv://rentwheels:tacobell@rentwheels.hmialql.mongodb.net/?appName=rentwheels}
spring.data.mongodb.database=${MONGODB_DATABASE:rentwheels}
server.port=${PORT:8080}
